// Turkey 2026 — Trip data (window globals so all babel scripts can read)

window.TRIP = {
  name: "TURKEY | 2026",
  subtitle: "A nine-day passage through the Aegean & the Bosphorus",
  startDate: "2026-08-20T00:25:00-04:00",
  endDate: "2026-08-29",
  crew: [
    { name: "Jonah",  initial: "J", color: "oklch(58% 0.14 38)",  role: "the planner" },
    { name: "Ryan",   initial: "R", color: "oklch(48% 0.06 110)", role: "the boat captain" },
    { name: "Soren",  initial: "S", color: "oklch(72% 0.13 75)",  role: "the historian" },
    { name: "Vicky",  initial: "V", color: "oklch(45% 0.08 220)", role: "the photographer" },
    { name: "Sam",    initial: "S", color: "oklch(38% 0.08 20)",  role: "the gourmand" },
    { name: "Andie",  initial: "A", color: "oklch(60% 0.13 70)",  role: "the early bird" },
  ],
};

// Stable Unsplash IDs (verified, with fallback solid swatches handled in component)
window.PHOTOS = {
  hero: "https://images.unsplash.com/photo-1527838832700-5059252407fa?w=2000&q=80",
  bodrum1: "https://images.unsplash.com/photo-1527838832700-5059252407fa?w=1600&q=80",
  bodrum2: "https://images.unsplash.com/photo-1530789253388-582c481c54b0?w=1200&q=80",
  bodrum3: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=1200&q=80",
  bodrum4: "https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=1200&q=80",
  bodrum5: "https://images.unsplash.com/photo-1559563362-c667ba5f5480?w=1200&q=80",
  istanbul1: "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?w=1600&q=80",
  istanbul2: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=1200&q=80",
  istanbul3: "https://images.unsplash.com/photo-1564507004663-b6dfb3c824d5?w=1200&q=80",
  istanbul4: "https://images.unsplash.com/photo-1527838832700-5059252407fa?w=1200&q=80",
  food1: "https://images.unsplash.com/photo-1561626423-a51b45aef0a1?w=1200&q=80",
  food2: "https://images.unsplash.com/photo-1597466765990-64ad1c35dafc?w=1200&q=80",
  boat: "https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=1600&q=80",
  market: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=1200&q=80",
  hammam: "https://images.unsplash.com/photo-1610116306796-6fea9f4fae38?w=1200&q=80",
  bosphorus: "https://images.unsplash.com/photo-1545459720-aac8509eb02c?w=1200&q=80",
};

window.ITINERARY = [
  {
    day: 1, label: "Day 01", date: "Thu Aug 20", city: "NYC → Bodrum",
    arc: "Departure",
    photo: window.PHOTOS.bodrum1,
    headline: "A red-eye east, and the Aegean by sundown.",
    summary: "Wheels up from JFK Wednesday night, connect through Istanbul, and land on the Bodrum peninsula in time for a late, slow first dinner.",
    blocks: [
      { time: "12:25 AM", title: "Depart JFK", note: "Turkish Airlines · TJFAIW · leave Wed night", kind: "travel" },
      { time: "5:15 PM",  title: "Land Istanbul", note: "Connect at IST · 1h30 layover", kind: "travel" },
      { time: "6:45 PM",  title: "IST → BJV", note: "Domestic hop to Bodrum", kind: "travel" },
      { time: "8:10 PM",  title: "Arrive Bodrum", note: "Transfer to Yalıkavak / hotel check-in", kind: "stay" },
      { time: "Late",     title: "First dinner", note: "TBD — see Bodrum food options", kind: "food", linkTo: { city: "Bodrum", category: "Food" } },
      { time: "After",    title: "Go out", note: "Wherever the night goes — see Bodrum spots", kind: "activity", linkTo: { city: "Bodrum" } },
    ],
  },
  {
    day: 2, label: "Day 02", date: "Fri Aug 21", city: "Bodrum",
    arc: "Macakizi day",
    photo: window.PHOTOS.bodrum2,
    headline: "Lunch at Macakizi. Sunset at ŞişkoPerihan.",
    summary: "Reserve loungers in advance. The lunch buffet is the meal of the trip. Dinner at ŞişkoPerihan in Yalıkavak — arguably the best sunset view on the peninsula, music picks up later.",
    blocks: [
      { time: "Morning",  title: "Slow start, hotel pool", note: "Coffee, swim, settle the jet lag", kind: "stay" },
      { time: "1:30 PM",  title: "Macakizi lunch buffet", note: "The drum, the bell, the cheesecake. Reserve loungers (restaurant@macakizi.com).", kind: "food" },
      { time: "Afternoon",title: "Beach + sea", note: "Stay through golden hour", kind: "activity" },
      { time: "Dinner",   title: "ŞişkoPerihan Yalıkavak", note: "Best sunset view in Bodrum · livelier vibe, music picks up later", kind: "food" },
      { time: "Late",     title: "Stay out", note: "Yalıkavak Marina drinks or Bodrum nightlife — see options", kind: "activity", linkTo: { city: "Bodrum" } },
    ],
  },
  {
    day: 3, label: "Day 03", date: "Sat Aug 22", city: "Bodrum",
    arc: "Boat day",
    photo: window.PHOTOS.boat,
    headline: "A gulet, a darty, a sunset DJ ritual.",
    summary: "Charter via Gulet Bookers. End at Scorpios Bodrum for the sunset set.",
    blocks: [
      { time: "Daytime",  title: "Beach club or boat", note: "Pick from the list — Macakizi, Lucca, Scorpios, or charter via Gulet Bookers", kind: "activity", linkTo: { city: "Bodrum", category: "Beach Club" } },
      { time: "5 PM",     title: "Scorpios Bodrum", note: "Beach club · sunset DJ ritual · Andie booked the table", kind: "activity" },
      { time: "Dinner",   title: "Bodrum dinner", note: "TBD — see restaurant options", kind: "food", linkTo: { city: "Bodrum", category: "Food" } },
    ],
  },
  {
    day: 4, label: "Day 04", date: "Sun Aug 23", city: "Bodrum",
    arc: "Mandarin day",
    photo: window.PHOTOS.bodrum3,
    headline: "Mandarin Oriental beach club. Then Gigi for dinner.",
    summary: "Mandarin Oriental beach club is the leading pick for the day — decide closer to the trip. Gigi Bodrum for dinner.",
    blocks: [
      { time: "Daytime",  title: "Mandarin Oriental beach club", note: "Top option for the day · day pass for non-guests · alternates: Bodrum Loft, charter via Gulet Bookers", kind: "activity", linkTo: { city: "Bodrum", category: "Beach Club" } },
      { time: "Dinner",   title: "Gigi Bodrum", note: "Considering for Sunday night · alternates in the Bodrum food list", kind: "food", linkTo: { city: "Bodrum", category: "Food" } },
    ],
  },
  {
    day: 5, label: "Day 05", date: "Mon Aug 24", city: "Bodrum → Istanbul",
    arc: "Into the city",
    photo: window.PHOTOS.istanbul1,
    headline: "Last swim, then wheels up to the city.",
    summary: "Check out of Bodrum. Late afternoon flight to Istanbul. First city dinner.",
    blocks: [
      { time: "Morning",  title: "Last beach + check out", note: "Final swim, pack, marina coffee", kind: "stay" },
      { time: "Afternoon",title: "BJV → Istanbul", note: "Late flight to IST, transfer to apartment", kind: "travel" },
      { time: "Evening",  title: "Istanbul check-in", note: "Drop bags, get oriented", kind: "stay" },
      { time: "Late",     title: "Istanbul dinner", note: "TBD — see Istanbul food options", kind: "food", linkTo: { city: "Istanbul", category: "Food" } },
    ],
  },
  {
    day: 6, label: "Day 06", date: "Tue Aug 25", city: "Istanbul",
    arc: "Open day",
    photo: window.PHOTOS.hammam,
    headline: "Open canvas. Pick from the city options.",
    summary: "Nothing locked in yet. Build the day from sights, food, and bars.",
    blocks: [
      { time: "Daytime",  title: "Sights or hammam", note: "See Istanbul activity + sight options", kind: "activity", linkTo: { city: "Istanbul", category: "Sight" } },
      { time: "Evening",  title: "Dinner", note: "TBD — see Istanbul food options", kind: "food", linkTo: { city: "Istanbul", category: "Food" } },
      { time: "Late",     title: "Drinks", note: "TBD — see Istanbul bar options", kind: "activity", linkTo: { city: "Istanbul", category: "Bar" } },
    ],
  },
  {
    day: 7, label: "Day 07", date: "Wed Aug 26", city: "Istanbul",
    arc: "Yeni Lokanta",
    photo: window.PHOTOS.istanbul2,
    headline: "The one fixed point this week.",
    summary: "Yeni Lokanta tasting menu. Build the rest of the day around it.",
    blocks: [
      { time: "Daytime",  title: "Sightseeing or shopping", note: "See Istanbul sight options", kind: "activity", linkTo: { city: "Istanbul", category: "Sight" } },
      { time: "8:30 PM",  title: "Yeni Lokanta", note: "Michelin Guide · tasting menu · yenilokanta.com — book 30+ days ahead", kind: "food" },
      { time: "Late",     title: "Drinks", note: "TBD — see Istanbul bar options", kind: "activity", linkTo: { city: "Istanbul", category: "Bar" } },
    ],
  },
  {
    day: 8, label: "Day 08", date: "Thu Aug 27", city: "Istanbul",
    arc: "Open day",
    photo: window.PHOTOS.bosphorus,
    headline: "Another open day. The city's yours.",
    summary: "Bosphorus cruise? Princes' Islands? Pick a path.",
    blocks: [
      { time: "Daytime",  title: "Sights, ferry, or hammam", note: "See activities + sights", kind: "activity", linkTo: { city: "Istanbul", category: "Activity" } },
      { time: "Evening",  title: "Dinner", note: "TBD — see Istanbul food options", kind: "food", linkTo: { city: "Istanbul", category: "Food" } },
      { time: "Late",     title: "Drinks", note: "TBD — see Istanbul bar options", kind: "activity", linkTo: { city: "Istanbul", category: "Bar" } },
    ],
  },
  {
    day: 9, label: "Day 09", date: "Fri Aug 28", city: "Istanbul",
    arc: "Last full day",
    photo: window.PHOTOS.istanbul3,
    headline: "Last full day. Stretch it.",
    summary: "Open canvas — fold in anything that didn't fit yet.",
    blocks: [
      { time: "Daytime",  title: "Neighborhoods or shopping", note: "See Istanbul neighborhood + shop picks", kind: "activity", linkTo: { city: "Istanbul", category: "Neighborhood" } },
      { time: "Evening",  title: "Dinner", note: "TBD — see Istanbul food options", kind: "food", linkTo: { city: "Istanbul", category: "Food" } },
      { time: "Late",     title: "Last rooftop", note: "Mikla, Bank Roof, or one we haven't hit yet", kind: "activity", linkTo: { city: "Istanbul", category: "Bar" } },
    ],
  },
  {
    day: 10, label: "Day 10", date: "Sat Aug 29", city: "Istanbul → NYC",
    arc: "Home",
    photo: window.PHOTOS.istanbul4,
    headline: "Last breakfast. Baklava run. Home.",
    summary: "Slow morning. Karaköy Güllüoğlu for baklava. Flight.",
    blocks: [
      { time: "Morning",  title: "Last Turkish breakfast", note: "Slow, lots of tea — Cafe Privato or Olden", kind: "food", linkTo: { city: "Istanbul", category: "Food" } },
      { time: "Late AM",  title: "Karaköy Güllüoğlu", note: "Baklava for the plane + home — non-negotiable", kind: "food" },
      { time: "Afternoon",title: "IST → JFK", note: "Group return", kind: "travel" },
    ],
  },
];

window.LODGING = [
  {
    city: "Bodrum",
    nights: 4,
    dates: "Aug 20 – 24",
    status: "decided",
    name: "Andie's Airbnb",
    pricing: "$6,262 · 4 nights",
    freeCancel: "Free cancellation until Jul 21",
    notes: "5 adults. Ask host about water taxi to the beach.",
    link: "https://www.airbnb.com/",
    photo: window.PHOTOS.bodrum1,
    coords: [37.0813, 27.4297],
  },
  {
    city: "Bodrum",
    nights: 4,
    dates: "Aug 20 – 24",
    status: "alternate",
    name: "G-Beyond, Yalıkavak",
    pricing: "$5,273 · 4 nights",
    notes: "JL friend rec. Alternate option — decide before Jul 21.",
    link: "https://g-beyond.com.tr/en/",
    photo: window.PHOTOS.bodrum2,
    coords: [37.1108, 27.2887],
  },
  {
    city: "Istanbul",
    nights: 5,
    dates: "Aug 24 – 28/29",
    status: "deciding",
    name: "Soho House Istanbul? (TBD)",
    pricing: "Exploring Soho House + apartments in Beyoğlu / Galata / Karaköy",
    notes: "Walking distance to old city, near tram for Sultanahmet. Final night flexible.",
    link: "https://www.sohohouse.com/houses/soho-house-istanbul",
    photo: window.PHOTOS.istanbul1,
    coords: [41.0256, 28.9744],
  },
];

window.SPOTS = [
  // BODRUM ─ Beach Clubs
  { city: "Bodrum", category: "Beach Club", name: "Macakizi", desc: "Hotel beach club · the lunch buffet is the meal of the trip. 1:30 PM drum signals open.", priority: "must", maps: "https://www.macakizi.com/" },
  { city: "Bodrum", category: "Beach Club", name: "Lucca Beach", desc: "Beach club + restaurant. Good first-night energy.", priority: "high", maps: "https://luccabeach.com/" },
  { city: "Bodrum", category: "Beach Club", name: "Limon Gümüşlük", desc: "10 min from Dereköy. One of the best views on the peninsula.", priority: "high", maps: "https://www.limongumusluk.com/limon-g%C3%BCm%C3%BC%C5%9Fl%C3%BCk" },
  { city: "Bodrum", category: "Beach Club", name: "Mandarin Oriental beach club", desc: "Day pass option for non-guests.", priority: "med", maps: "https://maps.google.com/?q=Mandarin+Oriental+Bodrum" },
  { city: "Bodrum", category: "Beach Club", name: "Scorpios Bodrum", desc: "Beach club · DJ sunset ritual. Saturday move. Table reservation recommended.", priority: "must", maps: "https://maps.google.com/?q=Scorpios+Bodrum" },
  { city: "Bodrum", category: "Beach Club", name: "Bodrum Loft / Paper Moon", desc: "Italian lunch interlude. Beach reserved for hotel guests but low season may bend. House chili oil.", priority: "high", maps: "https://maps.google.com/?q=Paper+Moon+Bodrum+Loft" },

  // BODRUM ─ Restaurants
  { city: "Bodrum", category: "Food", name: "Macakizi (dinner)", desc: "Beyond the buffet — dinner option, glamorous evening energy.", priority: "high", maps: "https://www.macakizi.com/" },
  { city: "Bodrum", category: "Food", name: "Bagarasi", desc: "Solid Bodrum dinner pick, low-key local.", priority: "high", maps: "https://maps.google.com/?q=Bagarasi+Bodrum" },
  { city: "Bodrum", category: "Food", name: "Dereköy Lokantasi", desc: "Modern Turkish in a quiet inland village. Like a chic friend's backyard.", priority: "must", maps: "https://maps.google.com/?q=Derekoy+Lokantasi+Bodrum" },
  { city: "Bodrum", category: "Food", name: "Atilay, Türkbükü", desc: "Fish right on the water. Local families, walk the port after.", priority: "high", maps: "https://maps.google.com/?q=Atilay+Turkbuku" },
  { city: "Bodrum", category: "Food", name: "Maçakızı Restaurant", desc: "One Michelin star (separate from the beach club lunch). Glamorous, exceptional.", priority: "high", maps: "https://maps.google.com/?q=Macakizi+Restaurant" },
  { city: "Bodrum", category: "Food", name: "ŞişkoPerihan Yalıkavak", desc: "Best sunset view in Bodrum. Music picks up later.", priority: "high", maps: "https://maps.google.com/?q=Sisko+Perihan+Yalikavak" },
  { city: "Bodrum", category: "Food", name: "Hakkasan Bodrum", desc: "International outpost · solid weeknight option.", priority: "med", maps: "https://maps.google.com/?q=Hakkasan+Bodrum" },
  { city: "Bodrum", category: "Food", name: "Zuma Bodrum", desc: "International outpost · reliable.", priority: "med", maps: "https://maps.google.com/?q=Zuma+Bodrum" },
  { city: "Bodrum", category: "Food", name: "Roka Bodrum", desc: "International outpost · solid.", priority: "med", maps: "https://maps.google.com/?q=Roka+Bodrum" },

  // BODRUM ─ Activity
  { city: "Bodrum", category: "Activity", name: "Gulet charter — Gulet Bookers", desc: "Full-day boat. Saturday move.", priority: "must", maps: "https://www.guletbookers.com/contact-us/" },
  { city: "Bodrum", category: "Activity", name: "Türkbükü Boardwalk", desc: "Walk the port, browse the shops, end at Atilay for fish.", priority: "high", maps: "https://maps.google.com/?q=Turkbuku+Boardwalk" },
  { city: "Bodrum", category: "Activity", name: "Yalıkavak Marina", desc: "The fancy marina — boutiques, sundowners, dinner.", priority: "high", maps: "https://maps.google.com/?q=Yalikavak+Marina" },
  { city: "Bodrum", category: "Activity", name: "5-hour Private Bodrum City Tour", desc: "Bodrum Castle, Underwater Museum (oldest known shipwrecks), Mausoleum of Halicarnassus.", priority: "med", maps: "https://maps.google.com/?q=Bodrum+Castle" },
  { city: "Bodrum", category: "Activity", name: "Boat trip to Kos", desc: "20-min hop to Greek islands. Easy day trip if anyone's keen.", priority: "low", maps: "https://maps.google.com/?q=Bodrum+to+Kos+ferry" },
  { city: "Bodrum", category: "Activity", name: "Gigi Bodrum", desc: "Late-night spot.", priority: "low", maps: "https://maps.google.com/?q=Gigi+Bodrum" },

  // BODRUM ─ Shop
  { city: "Bodrum", category: "Shop", name: "Yalıkavak Marina (shopping)", desc: "All the boutiques in one stretch. Easy afternoon.", priority: "high", maps: "https://maps.google.com/?q=Yalikavak+Marina" },
  { city: "Bodrum", category: "Shop", name: "No:81 Hotel boutique", desc: "Good boutique inside the hotel.", priority: "med", maps: "https://maps.google.com/?q=No+81+Hotel+Bodrum" },

  // ISTANBUL ─ Sights
  { city: "Istanbul", category: "Sight", name: "Hagia Sophia", desc: "The classic. Pre-book skip-the-line.", priority: "must", maps: "https://maps.google.com/?q=Hagia+Sophia" },
  { city: "Istanbul", category: "Sight", name: "Blue Mosque", desc: "Visit at dusk when the lights come on.", priority: "must", maps: "https://maps.google.com/?q=Blue+Mosque+Istanbul" },
  { city: "Istanbul", category: "Sight", name: "Topkapı Palace", desc: "Pre-book tickets. Don't skip the Harem.", priority: "must", maps: "https://maps.google.com/?q=Topkapi+Palace" },
  { city: "Istanbul", category: "Sight", name: "Basilica Cistern", desc: "Cool, dim, eerie. Quick stop.", priority: "high", maps: "https://maps.google.com/?q=Basilica+Cistern" },
  { city: "Istanbul", category: "Sight", name: "Grand Bazaar", desc: "Massive. Negotiate hard. Dollar goes far.", priority: "high", maps: "https://maps.google.com/?q=Grand+Bazaar+Istanbul" },
  { city: "Istanbul", category: "Sight", name: "Spice Market (Eminönü)", desc: "Short walk from Grand Bazaar. Smells alone are worth it.", priority: "high", maps: "https://maps.google.com/?q=Spice+Market+Istanbul" },
  { city: "Istanbul", category: "Sight", name: "Galata Tower", desc: "Worth seeing even if you don't go up.", priority: "high", maps: "https://maps.google.com/?q=Galata+Tower" },
  { city: "Istanbul", category: "Sight", name: "Taksim Square + Istiklal Street", desc: "Shopping, restaurants, side-street sites. Underground tram up.", priority: "med", maps: "https://maps.google.com/?q=Istiklal+Street+Istanbul" },
  { city: "Istanbul", category: "Sight", name: "Golden Horn + bridge", desc: "Cool to walk at night.", priority: "med", maps: "https://maps.google.com/?q=Golden+Horn+Istanbul" },
  { city: "Istanbul", category: "Sight", name: "Princes' Islands", desc: "Ferry, horse carriage, fish lunch. Optional half-day.", priority: "med", maps: "https://maps.google.com/?q=Princes+Islands+Istanbul" },
  { city: "Istanbul", category: "Sight", name: "Dolmabahçe Palace", desc: "Beautiful architecture, interesting museum.", priority: "low", maps: "https://maps.google.com/?q=Dolmabahce+Palace" },

  // ISTANBUL ─ Food
  { city: "Istanbul", category: "Food", name: "Yeni Lokanta ⭐", desc: "Top pick. Michelin Guide. Tasting menu is the move. Upscale, unpretentious.", priority: "must", maps: "https://yenilokanta.com" },
  { city: "Istanbul", category: "Food", name: "Mikla", desc: "Restaurant + rooftop bar. Mosques lit up at night. One of a kind. Call ahead.", priority: "must", maps: "https://maps.google.com/?q=Mikla+Restaurant+Istanbul" },
  { city: "Istanbul", category: "Food", name: "Murver", desc: "Wood fire oven. Great views of historical peninsula.", priority: "high", maps: "https://maps.google.com/?q=Murver+Istanbul" },
  { city: "Istanbul", category: "Food", name: "Roka Istanbul", desc: "Istanbul outpost of the international Roka brand.", priority: "high", maps: "https://maps.google.com/?q=Roka+Istanbul" },
  { city: "Istanbul", category: "Food", name: "Vogue Restaurant", desc: "Cafe, restaurant, and bar — versatile.", priority: "high", maps: "https://www.voguerestaurantandbar.com" },
  { city: "Istanbul", category: "Food", name: "Alaf", desc: "Primarily red meat. One of the top in the city.", priority: "high", maps: "https://maps.google.com/?q=Alaf+Istanbul" },
  { city: "Istanbul", category: "Food", name: "Karaköy Lokantası", desc: "Reliable Karaköy classic.", priority: "high", maps: "https://maps.google.com/?q=Karakoy+Lokantasi" },
  { city: "Istanbul", category: "Food", name: "Sunset Grill & Bar", desc: "After the Bosphorus cruise. Iconic views.", priority: "high", maps: "https://www.sunsetgrillbar.com" },
  { city: "Istanbul", category: "Food", name: "Hamdi", desc: "The go-to for kebabs in Istanbul.", priority: "med", maps: "https://maps.google.com/?q=Hamdi+Restaurant+Istanbul" },
  { city: "Istanbul", category: "Food", name: "Mangerie", desc: "Brunch. Bosphorus views.", priority: "med", maps: "https://maps.google.com/?q=Mangerie+Istanbul" },
  { city: "Istanbul", category: "Food", name: "Askana", desc: "Hole-in-the-wall. Best manti in the city.", priority: "high", maps: "https://maps.google.com/?q=Askana+Istanbul" },
  { city: "Istanbul", category: "Food", name: "Cafe Privato", desc: "Streetside Turkish breakfast.", priority: "high", maps: "https://maps.google.com/?q=Cafe+Privato+Istanbul" },
  { city: "Istanbul", category: "Food", name: "Olden", desc: "Recommended for breakfast.", priority: "high", maps: "https://maps.google.com/?q=Olden+Istanbul" },
  { city: "Istanbul", category: "Food", name: "Karaköy Güllüoğlu", desc: "The baklava spot. Non-negotiable.", priority: "must", maps: "https://maps.google.com/?q=Karakoy+Gulluoglu" },

  // ISTANBUL ─ Bars
  { city: "Istanbul", category: "Bar", name: "Mikla bar", desc: "Rooftop. Iconic views of lit-up old city + mosques. One of a kind.", priority: "must", maps: "https://maps.google.com/?q=Mikla+Restaurant+Istanbul" },
  { city: "Istanbul", category: "Bar", name: "Bank Roof Bar", desc: "Excellent rooftop bar.", priority: "high", maps: "https://www.thebankhotelistanbul.com" },
  { city: "Istanbul", category: "Bar", name: "Four Seasons rooftop (old city)", desc: "Rooftop overlooking the classic sites.", priority: "med", maps: "https://maps.google.com/?q=Four+Seasons+Sultanahmet" },
  { city: "Istanbul", category: "Bar", name: "Kiff (Bebek)", desc: "Clubbier of the two. Where people go now.", priority: "high", maps: "https://maps.google.com/?q=Kiff+Bebek" },
  { city: "Istanbul", category: "Bar", name: "Kaia (Bebek)", desc: "Divier of the two. Where people go now.", priority: "high", maps: "https://maps.google.com/?q=Kaia+Bebek" },
  { city: "Istanbul", category: "Bar", name: "Beyoğlu / Galatasaray bar hop", desc: "Main stretch for a night out.", priority: "high", maps: "https://maps.google.com/?q=Beyoglu+Istanbul" },

  // ISTANBUL ─ Activity
  { city: "Istanbul", category: "Activity", name: "Kılıç Ali Paşa Hamamı", desc: "16th-c bath. Pre-book. Top historic hamam.", priority: "must", maps: "https://maps.google.com/?q=Kilic+Ali+Pasa+Hamami" },
  { city: "Istanbul", category: "Activity", name: "Bosphorus cruise", desc: "Pick up alcohol before boarding.", priority: "must", maps: "https://maps.google.com/?q=Bosphorus+cruise" },
  { city: "Istanbul", category: "Activity", name: "Beşiktaş → Kadıköy ferry", desc: "European to Asian side. Combine with Moda + Bebek walks.", priority: "high", maps: "https://maps.google.com/?q=Besiktas+Ferry+Terminal" },

  // ISTANBUL ─ Neighborhoods
  { city: "Istanbul", category: "Neighborhood", name: "Moda", desc: "Asian side. One of the best neighborhoods to walk.", priority: "high", maps: "https://maps.google.com/?q=Moda+Istanbul" },
  { city: "Istanbul", category: "Neighborhood", name: "Bebek", desc: "European side. Sundowners + dinner spots.", priority: "high", maps: "https://maps.google.com/?q=Bebek+Istanbul" },
  { city: "Istanbul", category: "Neighborhood", name: "Nişantaşı", desc: "Fanciest area. Western + Turkish brands, cafes, bars.", priority: "high", maps: "https://maps.google.com/?q=Nisantasi+Istanbul" },
  { city: "Istanbul", category: "Neighborhood", name: "Karaköy", desc: "Where dinner happens.", priority: "high", maps: "https://maps.google.com/?q=Karakoy+Istanbul" },

  // ISTANBUL ─ Shop
  { city: "Istanbul", category: "Shop", name: "Atelier Rebul", desc: "The Aesop of Turkey — apothecary + skincare.", priority: "high", maps: "https://maps.google.com/?q=Atelier+Rebul+Istanbul" },
  { city: "Istanbul", category: "Shop", name: "Galataport", desc: "New shopping/dining on the water. Art museum nearby.", priority: "high", maps: "https://maps.google.com/?q=Galataport" },
  { city: "Istanbul", category: "Shop", name: "Les Merimes", desc: "Curated Turkish boutique.", priority: "med", maps: "https://maps.google.com/?q=Les+Merimes+Istanbul" },
  { city: "Istanbul", category: "Shop", name: "ANIM Living", desc: "Curated home goods.", priority: "med", maps: "https://maps.google.com/?q=ANIM+Living+Istanbul" },
  { city: "Istanbul", category: "Shop", name: "Aslı Filinta", desc: "Designer boutique.", priority: "med", maps: "https://maps.google.com/?q=Asli+Filinta+Istanbul" },
];

window.FLIGHTS = [
  { leg: "Outbound", from: "JFK", to: "IST", date: "Aug 20", depart: "12:25 AM", arrive: "5:15 PM", carrier: "Turkish Airlines", booking: "TJFAIW", who: "all" },
  { leg: "IST → BJV", from: "IST", to: "BJV", date: "Aug 20", depart: "6:45 PM", arrive: "8:10 PM", carrier: "Turkish Airlines", booking: "TJFAIW", who: "all" },
  { leg: "BJV → IST", from: "BJV", to: "IST", date: "Aug 24", depart: "Late afternoon", arrive: "—", carrier: "TBD", booking: "—", who: "all" },
  { leg: "Group return", from: "IST", to: "JFK", date: "Aug 29", depart: "—", arrive: "—", carrier: "TBD", booking: "—", who: "all" },
];

window.PACKING = [
  { cat: "Documents", items: ["Passport (6+ mo validity)", "Travel insurance card", "Backup credit card", "Vaccination record (just in case)", "Printed flight + hotel confirmations"] },
  { cat: "Beach (Bodrum)", items: ["3+ swimsuits", "Linen shirt + pants", "Cover-up / kaftan", "Espadrilles or sandals", "Reef-safe sunscreen", "Hat (the sun is brutal)", "Tote for boat day", "Polarized sunglasses"] },
  { cat: "Istanbul", items: ["Modest layer for mosques", "Long pants / midi skirt", "Headscarf (for Blue Mosque)", "Comfortable walking shoes", "One nice outfit (Mikla, Yeni)", "Light cardigan for AC"] },
  { cat: "Tech", items: ["Universal adapter (Type C/F)", "Portable charger", "AirTag in checked bag", "Headphones", "Camera + extra SD card"] },
  { cat: "Health", items: ["Imodium / Pepto", "Electrolyte packets", "Melatonin (jet lag)", "Reef-safe SPF 50", "After-sun lotion", "Bandaids / blister care", "Mosquito repellent"] },
];

window.GOOD_TO_KNOW = [
  { title: "Cash, not USD", body: "Turkey runs on Turkish lira. Most places do not accept USD. ATM out lira on arrival, keep small bills for taxis + tips." },
  { title: "Water taxis > taxis (Bodrum)", body: "Skip road traffic on the peninsula — water taxis run between coves. Ask the Airbnb host if they can arrange one to the beach." },
  { title: "Reserve everything", body: "Macakizi loungers, Scorpios tables, Yeni Lokanta, Topkapı tickets, Kılıç Ali Paşa hammam — all need pre-booking." },
  { title: "Mosque dress code", body: "Long pants / midi skirt, shoulders covered. Headscarf for women in mosques. Bring one for the Blue Mosque." },
  { title: "Tipping", body: "10% in restaurants is standard. Cash preferred, lira only." },
  { title: "Power", body: "Type C/F European plugs. Bring a universal adapter." },
];

window.SPOT_COORDS = {
  // Bodrum peninsula
  "Macakizi":                       [37.0853, 27.3417],
  "Lucca Beach":                    [37.0339, 27.4302],
  "Limon Gümüşlük":                 [37.0731, 27.2295],
  "Mandarin Oriental beach club":   [37.1138, 27.3033],
  "Scorpios Bodrum":                [37.0824, 27.3461],
  "Bodrum Loft / Paper Moon":       [37.0860, 27.3540],
  "Macakizi (dinner)":              [37.0853, 27.3417],
  "Bagarasi":                       [37.0357, 27.4290],
  "Dereköy Lokantasi":              [37.0480, 27.2660],
  "Atilay, Türkbükü":               [37.0853, 27.3380],
  "Maçakızı Restaurant":            [37.0853, 27.3417],
  "ŞişkoPerihan Yalıkavak":         [37.1108, 27.2887],
  "Hakkasan Bodrum":                [37.1138, 27.3033],
  "Zuma Bodrum":                    [37.1108, 27.2887],
  "Roka Bodrum":                    [37.1108, 27.2887],
  "Gulet charter — Gulet Bookers":  [37.0339, 27.4302],
  "Türkbükü Boardwalk":             [37.0860, 27.3540],
  "Yalıkavak Marina":               [37.1108, 27.2887],
  "5-hour Private Bodrum City Tour":[37.0319, 27.4290],
  "Boat trip to Kos":               [36.8930, 27.2900],
  "Gigi Bodrum":                    [37.0339, 27.4302],
  "Yalıkavak Marina (shopping)":    [37.1108, 27.2887],
  "No:81 Hotel boutique":           [37.1142, 27.2870],
  // Istanbul
  "Hagia Sophia":                   [41.0086, 28.9802],
  "Blue Mosque":                    [41.0054, 28.9768],
  "Topkapı Palace":                 [41.0115, 28.9833],
  "Basilica Cistern":               [41.0084, 28.9779],
  "Grand Bazaar":                   [41.0106, 28.9680],
  "Spice Market (Eminönü)":         [41.0166, 28.9706],
  "Galata Tower":                   [41.0256, 28.9744],
  "Taksim Square + Istiklal Street":[41.0369, 28.9850],
  "Golden Horn + bridge":           [41.0203, 28.9719],
  "Princes' Islands":               [40.8761, 29.1264],
  "Dolmabahçe Palace":              [41.0391, 29.0001],
  "Yeni Lokanta ⭐":                [41.0335, 28.9776],
  "Mikla":                          [41.0317, 28.9785],
  "Murver":                         [41.0235, 28.9740],
  "Roka Istanbul":                  [41.0788, 29.0438],
  "Vogue Restaurant":               [41.0470, 29.0072],
  "Alaf":                           [41.0380, 29.0080],
  "Karaköy Lokantası":              [41.0241, 28.9785],
  "Sunset Grill & Bar":             [41.0641, 29.0498],
  "Hamdi":                          [41.0173, 28.9710],
  "Mangerie":                       [41.0775, 29.0429],
  "Askana":                         [41.0335, 28.9810],
  "Cafe Privato":                   [41.0290, 28.9745],
  "Olden":                          [41.0325, 28.9779],
  "Karaköy Güllüoğlu":              [41.0240, 28.9785],
  "Mikla bar":                      [41.0317, 28.9785],
  "Bank Roof Bar":                  [41.0252, 28.9750],
  "Four Seasons rooftop (old city)":[41.0095, 28.9810],
  "Kiff (Bebek)":                   [41.0788, 29.0438],
  "Kaia (Bebek)":                   [41.0790, 29.0445],
  "Beyoğlu / Galatasaray bar hop":  [41.0335, 28.9776],
  "Kılıç Ali Paşa Hamamı":          [41.0245, 28.9809],
  "Bosphorus cruise":               [41.0220, 28.9745],
  "Beşiktaş → Kadıköy ferry":       [41.0420, 29.0070],
  "Moda":                           [40.9870, 29.0270],
  "Bebek":                          [41.0788, 29.0438],
  "Nişantaşı":                      [41.0470, 28.9930],
  "Karaköy":                        [41.0241, 28.9785],
  "Atelier Rebul":                  [41.0470, 28.9930],
  "Galataport":                     [41.0240, 28.9810],
  "Les Merimes":                    [41.0335, 28.9776],
  "ANIM Living":                    [41.0470, 28.9930],
  "Aslı Filinta":                   [41.0470, 28.9930],
};

window.DECISIONS = [
  { id: "macakizi",     q: "Email restaurant@macakizi.com — Fri Aug 21 lunch + loungers", status: "open", note: "Reserve well ahead." },
  { id: "scorpios",     q: "Book Scorpios Bodrum (Sat Aug 22) — tickets vs table", status: "open", note: "Check what's required." },
  { id: "bjv-ist",      q: "Book Bodrum → Istanbul flight (Mon Aug 24, late)", status: "open", note: "Late afternoon BJV→IST." },
  { id: "ist-stay",     q: "Decide Istanbul lodging — explore Soho House", status: "open", note: "Otherwise apartment in Beyoğlu / Galata." },
  { id: "topkapi",      q: "Pre-book Topkapı Palace tickets", status: "open", note: "Skip-the-line." },
  { id: "hammam",       q: "Book Kılıç Ali Paşa Hamamı", status: "open", note: "Pre-book a slot for Tue evening." },
  { id: "yeni",         q: "Yeni Lokanta reservation", status: "open", note: "Book 30+ days ahead." },
  { id: "bodrum-hotel", q: "Bodrum lodging — Airbnb or G-Beyond?", status: "open", note: "Andie booked the Airbnb (cancellable until July 21). G-Beyond ($5,273, JL rec) held as alternate." },
  { id: "return",       q: "Group return: Aug 29", status: "decided", note: "All flying back together." },
];
